#! /bin/sh
### BEGIN INIT INFO
# Provides:          myapp
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: My application
# Description:       
#
### END INIT INFO

/path/to/myapp/dep/estarter/priv/init-d $1
